TrainingArguments: 
    num_train_epochs: 1
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 4
    warmup_steps: 100
    weight_decay: 0.01
    logging_steps: 160
    evaluation_strategy: steps
    eval_steps: 160
    load_best_model_at_end : True
    save_steps : 160
    seed : 42
    num_labels : 3