artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://docs.google.com/uc?export=download&id=11inZrKHJ-Zj68qsw8o-RicSadEhz-E24
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


