artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://docs.google.com/uc?export=download&id=11inZrKHJ-Zj68qsw8o-RicSadEhz-E24
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data
  tokenizer_name: cardiffnlp/twitter-roberta-base-sentiment-latest

model_trainer:
  root_dir: artifacts/model_training
  data_path: artifacts/data_transformation
  model_ckpt: cardiffnlp/twitter-roberta-base-sentiment-latest
  log_dir : logs

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/test
  model_path: artifacts/model_training/model
  tokenizer_path: artifacts/model_training/tokenizer
  metrics_file_name: artifacts/model_evaluation/metrics.csv 